### ISSUE TITLE
Failure to compile with gcc-14.1.0

### ISSUE THREAD

**Issue by heitbaum** [libretro/mame2003-plus-libretro#1721]
Error 1
```
src/drivers/asuka.c: In function 'init_earthjkr':
src/drivers/asuka.c:1461:25: error: initialization of 'data16_t *' {aka 'short unsigned int *'} from incompatible pointer type 'UINT8 *' {aka 'unsigned char *'} [-Wincompatible-pointer-types]
 1461 |         data16_t *rom = memory_region(REGION_CPU1);
      |                         ^~~~~~~~~~~~~
```
https://github.com/libretro/mame2003-plus-libretro/blob/95165d56389862cae9bad2b361667e19b0cb0d44/src/drivers/asuka.c#L1461

error 2
```
src/common.c:439:46: error: assignment to 'INT16 *' {aka 'short int *'} from incompatible pointer type 'signed char *' [-Wincompatible-pointer-types]
  439 |                         flac_file.write_data = result->data;
      |                                              ^
```
https://github.com/libretro/mame2003-plus-libretro/blob/95165d56389862cae9bad2b361667e19b0cb0d44/src/common.c#L439

error 3
```
src/drivers/dietgo.c:166:56: error: initialization of 'size_t *' {aka 'long unsigned int *'} from incompatible pointer type 'unsigned int *' [-Wincompatible-pointer-types]
  166 |         { 0x280000, 0x2807ff, MWA16_RAM, &spriteram16, &spriteram_size },
      |                                                        ^
```
https://github.com/libretro/mame2003-plus-libretro/blob/95165d56389862cae9bad2b361667e19b0cb0d44/src/drivers/dietgo.c#L166

**Comment by mahoneyt944** [comment]
@heitbaum try this : https://github.com/libretro/mame2003-plus-libretro/commit/ab725a7f30a133551742b400089e8fffdf29d84a

**Comment by heitbaum** [comment]
> @heitbaum try this : [ab725a7](https://github.com/libretro/mame2003-plus-libretro/commit/ab725a7f30a133551742b400089e8fffdf29d84a)

Tested. Compile successful now. 👍
